extends Node

const PLAYER_SHIP_SPEED = 150
const PLAYER_WALK_SPEED = 100
const PLAYER_JUMP_SPEED = 300
const PLAYER_STARTING_HEALTH = 5.0
const PLAYER_HIT_INVULN_IN_SECS = 1.5
const PLAYER_FIRE_RATE = 0.25

const EYE_BOSS_STARTING_HEALTH = 50.0
const EYE_BOSS_EYE_BULLET_DAMAGE = 1.0

const ENERGY_TURRET_DAMAGE = 1.2

const MISSILE_DAMAGE = 1.5

const SPIDER_DAMAGE = 1.0
const SPIDER_SPEED = 30

const BIG_SPIDER_SPEED = 40
const BIG_SPIDER_HEALTH = 30


## Underground

const ANEMONE_SPEED = 25