extends Node

const PLAYER_SHIP_SPEED = 150
const PLAYER_WALK_SPEED = 100
const PLAYER_JUMP_SPEED = 300
const PLAYER_STARTING_HEALTH = 5.0
const PLAYER_HIT_INVULN_IN_SECS = 1.5
const PLAYER_FIRE_RATE = 0.25

const EYE_BOSS_STARTING_HEALTH = 50.0
const EYE_BOSS_EYE_BULLET_DAMAGE = 1.0
const EYE_BOSS_SCORE = 10000

const ENERGY_TURRET_DAMAGE = 1.2
const ENERGY_TURRET_SCORE = 20000

const MISSILE_DAMAGE = 1.5
const MISSILE_SCORE = 500

const SPIDER_DAMAGE = 1.0
const SPIDER_SPEED = 30
const SPIDER_SCORE = 300

const SPACE_EEL_DAMAGE = 1.0
const SPACE_EEL_SPEED = 30
const SPACE_EEL_SCORE = 1000

const BIG_SPIDER_SPEED = 40
const BIG_SPIDER_HEALTH = 30
const BIG_SPIDER_SCORE = 5000

const BUZZSAW_SCORE = 1000